apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: wp-labs
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: student
  RABBITMQ_DEFAULT_PASS: student_secure_rabbit_pass_change_in_prod
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-erlang-cookie
  namespace: wp-labs
type: Opaque
stringData:
  RABBITMQ_ERLANG_COOKIE: rabbitmq-lab-cookie-2024
