apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: wp-labs
type: Opaque
stringData:
  MONGO_ROOT_USER: admin
  MONGO_ROOT_PASSWORD: secret
  MONGO_URI: "mongodb://admin:secret@mongodb.wp-labs.svc.cluster.local:27017/wp_labs?authSource=admin"
