apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: wp-labs
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:secret@mongodb.wp-labs.svc.cluster.local:27017/wp_labs?authSource=admin"
  JWT_ACCESS_SECRET: "your_access_secret_key_min_32_chars"
  JWT_REFRESH_SECRET: "your_refresh_secret_key_min_32_chars"
  REDIS_PASSWORD: "redis_secure_password_change_in_prod"
  MINIO_ACCESS_KEY: "minio_admin"
  MINIO_SECRET_KEY: "minio_secure_password_change_in_prod"
  RABBITMQ_PASS: "student_secure_rabbit_pass_change_in_prod"
  SMTP_USER: "your_email@yandex.ru"
  SMTP_PASS: "your_app_password"
  SMTP_FROM: "your_email@yandex.ru"
  YANDEX_CLIENT_ID: "your_yandex_client_id"
  YANDEX_CLIENT_SECRET: "your_yandex_client_secret"
